version: '3.3'

services:
   rtmp:
     image: longshot902/rtmp
     volumes:
       - ./stream:/html
     restart: unless-stopped
     ports:
       - "80:80"
       - "1935:1935"
     networks:
       - stream-network

   encoder:
     depends_on:
       - rtmp
     image: jrottenberg/ffmpeg
     restart: unless-stopped
     volumes:
       - ./stream:/stream
     command:  -i rtmp://rtmp/live -c:v libx264 -crf 21 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -ac 2 -b:a 128k -movflags faststart -flags -global_header -hls_flags delete_segments /stream/live.m3u8
     networks:
       - stream-network

networks:
   stream-network:
       driver:  bridge