version: '3'

services:
   rtmp:
     image: netwarlan/rtmp
     volumes:
       - ./stream:/html
     restart: unless-stopped
     ports:
       - "80:80"
       - "1935:1935"
     networks:
       - stream-network

   encoder:
     depends_on:
       - rtmp
     image: jrottenberg/ffmpeg
     restart: unless-stopped
     volumes:
       - ./stream:/stream
     command: -i rtmp://rtmp/live -c:a aac -ar 48000 -b:a 128k -c:v h264 -profile:v main -crf 20 -g 48 -keyint_min 48 -sc_threshold 0 -b:v 2500k -maxrate 2675k -bufsize 3750k -f hls -hls_list_size 5 -hls_flags delete_segments -hls_time 6 /stream/live.m3u8
     networks:
       - stream-network

networks:
   stream-network:
       driver:  bridge